services:
  puller:
    image: mastodon_view:latest
    ports:
      - "50051:50051"
    command: ["/puller"]

  view1:
    image: mastodon_view:latest
    ports:
      - "8081:8081"
    depends_on:
      - puller
    command: ["/view1", "puller"]

  view2:
    image: mastodon_view:latest
    ports:
      - "8082:8082"
    depends_on:
      - puller
    command: ["/view2", "puller"]
